version: "2"
linters:
  enable:
    - bodyclose
    - errorlint
    - godot
    - lll
    - nakedret
    - predeclared
    - revive
    - staticcheck
    - usestdlibvars
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
