linters:
  enable: # additional linters
    - errorlint
    - bodyclose
    - godot
    - gofmt
    - gofumpt
    - goimports
    - lll
    - nakedret
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - usestdlibvars
    - whitespace
